commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grabgamezzz.urls')),
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

grabgamezzz/models.py
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db import models

# Create your models here.
class User(AbstractUser):

    def __str__(self):
        return self.username.capitalize()


class Giveaway(models.Model):
    title=models.CharField(max_length=128)
    image=models.URLField()
    description=models.TextField(max_length=2048)
    instructions=models.TextField(max_length=512)
    type=models.CharField(max_length=20)
    platforms=models.CharField(max_length=128)
    worth=models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    url=models.URLField()
    collected=models.ManyToManyField(User, blank=True, related_name='collectors')
    published_date=models.DateTimeField(default=timezone.now)
    expiry_date=models.DateField(blank=True, null=True)
    gp_id=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title


class Lastchecked(models.Model):
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')

grabgamezzz/views.py
import json
import operator
from functools import reduce
from requests import get
from random import randint, sample, choice
from datetime import date, datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.hashers import check_password, make_password
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import User, Giveaway, Lastchecked

# Create your views here.


""" Paginate (divide output by pages) """
def paginate(request, listing): 
    paginator = Paginator(listing, 12)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


""" Populate database using gamepower.com API """
def populate():
    # Get giveaways from gamepower.com
    givs = get('https://www.gamerpower.com/api/giveaways', headers={'Accept': 'application/json'}).json()[::-1]
    # Get recorded giveaway ids from database
    recorded_ids = Giveaway.objects.values_list('gp_id', flat=True)
    for giv in givs:
        # If giveaway already recorded, skip
        if giv['id'] in recorded_ids:
            continue
        else:
            # Set a new giveaway
            title = giv['title']
            image = giv['image']
            description = giv['description']
            instructions = giv['instructions']
            type = giv['type']
            platforms = giv['platforms']
            url = giv['open_giveaway']
            published_date = datetime.strptime(giv['published_date'], '%Y-%m-%d %H:%M:%S')
            gp_id = giv['id']
            # Get all registered users from database
            users = User.objects.values_list('id', flat=True)
            count = users.count()
            # Set giveaway author from registered users randomly
            author = User.objects.get(pk=choice(users))
            # Record new giveaway to database
            new_giv = Giveaway.objects.create(title=title, image=image, description=description, instructions=instructions, type=type, platforms=platforms, url=url, published_date=published_date, gp_id=gp_id, author=author)
            # Set giveaway collectors from registered users randomly
            new_giv.collected.set(sample(list(users), randint(0, count)))
            # Set giveaway worth and expiry_date fields, where available
            if giv['worth'] != 'N/A':
                new_giv.worth = float(giv['worth'].replace('$', ''))
            if giv['end_date'] != 'N/A':
                new_giv.expiry_date = date.fromisoformat(giv['end_date'].split(' ')[0])
            new_giv.save(update_fields=['worth', 'expiry_date'])


def index(request):
    # If database last checked before today, populate (update) it
    if Lastchecked.objects.filter(date__lt=date.today()).exists():
        try:
            populate()
            Lastchecked.objects.first().save()
        except:
            Lastchecked.objects.first().save()
    # Get all giveaways from database
    givs = Giveaway.objects.all()
    # If query parameters set...
    if request.GET.get('by') or request.GET.get('q'):
        #...process query and prepare giveaway list and message
        givs, message = sort_filter(request, givs)
    else:
        #...prepare giveaway list and message
        givs = givs.order_by('-published_date')
        message = f'{givs.count()} Giveaways await your pleasure, {request.user}!'
    # Divide output by pages
    page_obj = paginate(request, givs)
    return render(request, 'grabgamezzz/index.html', {
        'page_obj': page_obj,
        'message': message
    })

def login_view(request):
    if request.method == 'POST':

        # Attempt to sign user in
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.info(request, 'Invalid username and/or password.')
            return render(request, 'grabgamezzz/login.html', {
                'username': username
            })
    else:
        return render(request, 'grabgamezzz/login.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        new_user = dict(username=username, first_name=first_name, last_name=last_name, email=email)
        # Ensure password matches confirmation
        password = request.POST.get('password')
        confirmation = request.POST.get('confirmation')
        if password != confirmation:
            messages.info(request, 'Passwords must match.')
            return render(request, 'grabgamezzz/register.html', {
                'user': new_user
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            user.first_name = first_name
            user.last_name = last_name
            user.save(update_fields=['first_name', 'last_name'])

        except IntegrityError:
            messages.info(request, 'Username already taken.')
            return render(request, 'grabgamezzz/register.html', {
                'user': new_user
            })
        login(request, user)
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'grabgamezzz/register.html')


""" Sort and filter giveaways as requested """
def sort_filter(request, givs):
    # Get sort and order parameters, if any
    by = request.GET.get('by', default='published_date')
    order = request.GET.get('order', default='-')
    order_by = order + by
    # Get search query, if any
    q = request.GET.get('q')
    if q:
        givs = givs.filter(title__icontains=q)
        mq = f'for "{q}" query'
    else:
        mq = ''
    # Get filter parameters and filter
    platforms = request.GET.getlist('platforms')
    if platforms:
        givs = givs.filter(reduce(operator.or_, (Q(platforms__icontains=x) for x in platforms)))
    status = request.GET.getlist('status')
    if len(status) == 1:
        today = date.today()
        mstatus = status[0]
        if mstatus == 'expired':
            givs = givs.filter(expiry_date__lt=today)
        else:
            givs = givs.exclude(expiry_date__lt=today)
    else:
        mstatus = ''
    type = request.GET.getlist('type')
    if type:
        givs = givs.filter(reduce(operator.or_, (Q(type__icontains=x) for x in type)))
    givs = givs.order_by(order_by)
    # Make a message on sort, filter and search results
    msorted = {
        'published_date': 'publication date',
        'expiry_date': 'expiry date',
        'worth': 'worthiness',
        'title': 'title'
        }
    morder = {
        '': 'ascending',
        '-': 'descending'
    }
    mtype = f'of {", ".join(type)} {"type" if len(type)==1 else "types"}' if type else ''
    mplatforms = f'for {", ".join(platforms)} {"platform" if len(platforms)==1 else "platforms"}' if platforms else ''
    msort = f'sorted by {msorted[by]} in {morder[order]} order'
    if 'collection' in request.path:
        mcollection = f"in {request.user}'s collection"
    else:
        mcollection = ''
    message = f'Found {givs.count()} {mstatus} {"Giveaway" if givs.count() == 1 else" Giveaways"} {mtype} {mplatforms} {msort} {mq} ' +  mcollection
    return givs, message


def collection(request):
    user = request.user
    # Get all giveaways in user's collection
    collection = Giveaway.objects.filter(collected__username__icontains=user).order_by('-published_date')
    # If query parameters set...
    if request.GET.get('by') or request.GET.get('q'):
        #...process query and prepare giveaway list and message
        collection, message = sort_filter(request, collection)
    else:
        #...prepare giveaway list and message
        message = f'Collection of {collection.count()} {"Giveaway" if collection.count() == 1 else" Giveaways"} selected by {user}'
    # Divide output by pages
    page_obj = paginate(request, collection)
    return render(request, 'grabgamezzz/index.html', {
        'page_obj': page_obj,
        'message': message,
        })

"""Add/remove user to/from giveaway collectors"""
@csrf_exempt
def collect(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        id = data.get('id')
        user = request.user
        giv = Giveaway.objects.get(pk=id)
        if user in giv.collected.all():
            giv.collected.remove(user)
        else:
            giv.collected.add(user)
        giv.save()
        count = giv.collected.count()
        return JsonResponse({'count': count})
    else:
        return HttpResponse('Error: Method must be "POST"!')


def profile(request):
    user = User.objects.get(pk=request.user.id)
    if request.method == 'GET':
        # Render user's profile page
        return render(request, 'grabgamezzz/profile.html', {
            'user': user,
        })
    else:
        # Find out what to change
        posted_username = request.POST.get('username')
        if posted_username:
            # Change user's data
            user.username = posted_username
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.save()

grabgamezzz/templates/grabgamezzz/index.html
{% extends 'grabgamezzz/layout.html' %}

{% block title %}
  Giveaways
{% endblock %}

{% block main %}

  <!--Action Message, if any-->
  {% if messages %}
  <div id="actMessage" style="display: none">
    {% for message in messages %}
      {% if message.tags %} {{ message }} {% endif %}
    {% endfor %}
  </div>
  {% endif %}

  <!--Database Query Message, if any-->
  {% if message %}
  <div class="d-flex flex-row mb-3">
    <div class="h5 me-3">
      {{ message }}
    </div>
    <button class="btn btn-warning btn-sm text-nowrap align-self-start" type="button" data-bs-toggle="offcanvas" data-bs-target="#sortFilter" aria-controls="sortFilter">Sort &amp; Filter</button>
  </div>
  {% endif %}

  <!--Giveaway View Modal-->
  {% include 'grabgamezzz/includes/giveaway_view_modal.html' %}
  <!--End of Giveaway View Modal-->

  <!--Sort and Filter Offcanvas-->
  {% include 'grabgamezzz/includes/sort_filter_offcanvas.html' %}
  <!--End of Sort and Filter Offcanvas-->

  <!--Giveaways Section-->
  <div class="row">
  {% for giv in page_obj %}
    {% include 'grabgamezzz/includes/giveaway_card.html' %}
  {% endfor %}
  </div>
  <!--End of Giveaways Section-->

  <!--Pagination Section-->
  {% if page_obj %}
    {% include 'grabgamezzz/includes/pagination.html' %}
  {% endif %}
  <!--End of Pagination Section-->

{% endblock %}

grabgamezzz/templates/grabgamezzz/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="GrabGamezz is a free game giveaways site developed as a final project for CS50W course">
    <meta name="author" content="Yuriy Melnykov">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'grabgamezzz/grabgamezzz.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cc0371904f.js" crossorigin="anonymous"></script>
    <script>
      var userIsAnonymous = {{ user.is_anonymous|yesno:'true, false' }};
    </script>
    <script src="{% static 'grabgamezzz/grabgamezzz.js' %}"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'grabgamezzz/favicon.ico' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>

  <body>

    <!--Webpage Header-->
    <header class="container-fluid sticky-top bg-primary">
      <div class="container">
        <!--Navigation Bar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <!--Website Logo-->
            <a class="navbar-brand" href="{% url 'index' %}"><span class="h1 text-white"><i class="fa-solid fa-gamepad"></i> GrabGamezzz</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
                <!--Webpage Links-->
                {% url 'index' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Giveaways</a>
                </li>
              {% if user.is_authenticated %}
                {% url 'collection' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Collection</a>
                </li>
                {% url 'profile' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Profile</a>
                </li>
                {% url 'submit' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Submit</a>
                </li>
                {% url 'logout' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Log out</a>
                </li>
              {% else %}
                {% url 'login' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Log in</a>
                </li>
                {% url 'register' as url %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">Register</a>
                </li>
              {% endif %}
              </ul>
              <!--Current User Name and Icon-->
              {% if user.is_authenticated %}
              <a href="{% url 'profile' %}" class="nav-link text-white text-truncate me-3"><i class="fa-solid fa-user me-2"></i>{{ request.user }}</a>
              <!--Search Bar available on Giveaways and Collection pages-->
              {% endif %}
              {% url 'index' as url1 %}
              {% url 'collection' as url2 %}
              {% if request.path == url1 or request.path == url2 %}
              <form class="d-flex" action="{{request.path}}" method="get" role="search">
                <input class="form-control-sm me-2" type="search" placeholder="Search for Giveaways" name="q" aria-label="Search">
                <button class="btn btn-secondary btn-sm me-2" type="submit">Search</button>
              </form>
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--End of Webpage Header-->

    <!--Webpage Main Content-->
    <main class="container mt-3">
      {% block main %}
      {% endblock %}
    </main> 
    <!--End of Webpage Main Content-->
  
    <!--Webpage Footer-->
    <footer class="my-3 small text-center text-muted">
      Copyright &#169; 2023 by <a href="mailto:ymelnykov@gmail.com">Yuriy Melnykov</a>. 
      All rights reserved. All trademarks are property of their respective owners.
    </footer>
    <!--End of Webpage Footer-->
  
  </body>
  
</html>

grabgamezzz/templates/grabgamezzz/login.html
{% extends "grabgamezzz/layout.html" %}

{% block title %}
    Log in
{% endblock %}

{% block main %}

    <!--Action Message, if any-->
    {% if messages %}
    <div id="actMessage" style="display: none">
      {% for message in messages %}
      {% if message.tags %} {{ message }} {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <h2>Log in</h2>

    <!--Login Form-->
    <div class="row mb-3">
        <div class="col-sm-2"></div>
        <div class="col-sm-6 small text-muted">Fields marked with "*" are required.</div>
    </div>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_username">Username*:</label>
            <div class="col-sm-6">
                <input class="form-control form-control-sm" type="text" name="username" value="{{ username }}" maxlength="150" id="id_username" autofocus required>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_password">Password*:</label>
            <div class="col-sm-6">
                <input class="form-control form-control-sm" type="password" name="password" maxlength="150" id="id_password" required>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <input class="btn btn-primary" type="submit" value="Log in">
            </div>
        </div>
    </form>
    <!--Register Link-->
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            Don't have an account? <a href="{% url 'register' %}">Register here.</a>
        </div>
    </div>

{% endblock %}

grabgamezzz/templates/grabgamezzz/profile.html
{% extends "grabgamezzz/layout.html" %}

{% block title %}
    Profile
{% endblock %}

{% block main %}

    <!--Action Message, if any-->
    {% if messages %}
    <div id="actMessage" style="display: none">
        {% for message in messages %}
        {% if message.tags %} {{ message }} {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    <h2>Profile</h2>

    <!--Data Change Section-->
    <div class="row border-top pt-3 mt-3">
        <h4>Data change</h4>
        <p>Here you can change your personal data.</p>
        <div class="row mb-3">
            <div class="col-sm-2"></div>
            <div class="col-sm-6 small text-muted">Fields marked with "*" are required.</div>
        </div>
        <form action="{% url 'profile' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_username">Username*:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="text" name="username" maxlength="150" id="id_username" value="{{ user.username }}" required>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10 text-muted" style="font-size: 0.75rem" id="id_username_helptext">
                    150 characters or fewer. Letters, digits and @/./+/-/_ only.
                </div>
            </div>
            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_first_name">First name:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="text" name="first_name" maxlength="150" id="id_first_name" value="{{ user.first_name }}">
                </div>
            </div>
            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_last_name">Last name:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="text" name="last_name" maxlength="150" id="id_last_name" value="{{ user.last_name }}">
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_email">Email*:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="email" name="email" maxlength="254" id="id_email" value="{{ user.email }}" required>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <input class="btn btn-primary btn-sm" type="submit" value="Save Data">
                </div>
            </div>
        </form>
    </div>
    <!--End of Data Change Section-->
    
    <!--Password Change Section-->
    <div class="row border-top pt-3 mt-3">
        <h4>Password change</h4>
        <p>Please enter your old password, for security purposes, and then enter your new password twice to verify you typed it in correctly.</p>
        <div class="row mb-3">
            <div class="col-sm-2"></div>
            <div class="col-sm-6 small text-muted">Fields marked with "*" are required.</div>
        </div>
        <form action="{% url 'profile' %}" method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_old_password">Old password*:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="password" name="old_password" maxlength="150" id="id_old_password" required>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_new_password1">New password*:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="password" name="new_password1" maxlength="150" id="id_new_password1" required>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-2"></div>
                <div class="col-sm-10 text-muted" style="font-size: 0.75rem" id="id_new_password1_helptext">
                    <ul>
                        <li>Your password can’t be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can’t be a commonly used password.</li>
                        <li>Your password can’t be entirely numeric.</li>
                    </ul>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label fw-semibold" for="id_new_password2">Confirm new password*:</label>
                <div class="col-sm-6">
                    <input class="form-control form-control-sm" type="password" name="new_password2" maxlength="150" id="id_new_password2" required>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <input class="btn btn-secondary btn-sm" type="submit" value="Change Password">
                </div>
            </div>
        </form>
    </div>
    <!--End of Password Change Section-->

{% endblock %}

grabgamezzz/templates/grabgamezzz/submit.html
{% extends "grabgamezzz/layout.html" %}

{% block title %}
    Submit
{% endblock %}

{% block main %}

    <!--Action Message, if any-->
    {% if act_message %}
    <div id="actMessage" style="display: none">
        {{ act_message }}
    </div>
    {% endif %}
    
    <h2>Submit</h2>
    <p>Here you can submit a new giveaway.</p>

    <!--Submit Form-->
    <div class="row my-3">
        <div class="col-sm-2"></div>
        <div class="col-sm-6 small text-muted">Fields marked with "*" are required.</div>
    </div>
    <form action="{% url 'submit' %}" method="post">
    {% csrf_token %}
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_url">Giveaway URL*:</label>
            <div class="col-sm-6">
                <input class="form-control form-control-sm" type="url" name="url" id="id_url" placeholder="https://www.example.com/giveaway" required>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_title">Title*:</label>
            <div class="col-sm-6">
                <input class="form-control form-control-sm" type="text" name="title" id="id_title" placeholder="Concise, but descriptive title" required>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_image">Image URL:</label>
            <div class="col-sm-6">
                <input class="form-control form-control-sm" type="url" name="image" id="id_image" placeholder="https://www.example.com/image.jpg">
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_description">Description*:</label>
            <div class="col-sm-6">
                <textarea class="form-control form-control-sm" name="description" id="id_description" rows="5" placeholder="Describe the Giveaway briefly here" required></textarea>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_instructions">Instructions*:</label>
            <div class="col-sm-6">
                <textarea class="form-control form-control-sm" name="instructions" id="id_instructions" rows="5" placeholder="Provide stepwise instructions on how to get the Giveaway" required></textarea>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_type">Type*:</label>
            <div class="col-sm-6">
                <select class="form-select form-select-sm" name="type" id="id_type" required>
                    <option value="">Select Giveaway type</option>
                    <option value="DLC">DLC</option>
                    <option value="Early Access">Early Access</option>
                    <option value="Game">Game</option>
                </select>
            </div>
        </div>
        <div class="row">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_platforms">Platforms*:</label>
            <div class="col-sm-6">
                <select class="form-select form-select-sm" name="platforms" id="id_platforms" multiple required>
                    <option value="">Select appropriate platforms</option>
                    {% for platform in platforms %}
                    <optgroup label="{{platform.type}}">
                        {% for name in platform.names %}
                        <option value="{{name}}">{{name}}</option>
                        {% endfor %}
                    </optgroup>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-2"></div>
            <div class="col-sm-6 text-muted" style="font-size: 0.75rem" id="id_platforms_helptext">
                Holding down the <code>Ctrl</code> key, use the <code>Up</code> and <code>Down</code> cursor keys to change the "focused" select option and press <code>Space</code> to select/deselect "focused" select options.
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_worth">Worth (price):</label>
            <div class="col-sm-6">
                <div class="input-group">
                    <span class="input-group-text">$</span>
                    <input type="number" min="0.00" step="0.01" class="form-control form-control-sm" name="worth" id="id_worth" placeholder="0.00">
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label fw-semibold" for="id_expiry_date">Expiry date:</label>
            <div class="col-sm-6">
                <input class="form-control form-control-sm" type="date" name="expiry_date" id="id_expiry_date">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <input class="btn btn-primary btn-sm" type="submit" value="Submit Giveaway">
            </div>
        </div>
    </form>

{% endblock %}